# LiRA Debugging Note

In [2]:
import os
import numpy as np

## Train

In [3]:
# TODO

## Inference

In [47]:
# path = "exp/resnet50_cifar10"
path = "exp/resnet50_cifar10/upstream"

keep = np.load(os.path.join(path, "keep_sampled.npy"))
opredictions = np.load(os.path.join(path, "logits.npy"))

In [48]:
print(keep.shape)
print(keep)

(1000,)
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True 

In [49]:
print(opredictions.shape)
opredictions

(1000, 1, 10)


array([[[-1.70638955, -1.52455866, -0.38727209, ...,  4.03921127,
          0.13444337,  0.34692135]],

       [[-0.89708561, -0.33314255, -1.4771452 , ..., -1.86064482,
         10.06783581, -0.58932614]],

       [[ 9.52553463, -1.6094985 , -1.16022491, ..., -1.4083668 ,
          1.72124493, -0.9858256 ]],

       ...,

       [[-1.32152915,  9.40876675, -2.32015467, ..., -1.75141966,
          1.62117207,  0.7278114 ]],

       [[-2.41617107, -2.1342113 , -1.42201066, ..., -1.82215476,
         -1.72431898, -1.80677962]],

       [[-1.42849624, -2.11865568, -0.69884688, ..., -0.84217989,
          0.230249  , -1.44698322]]])

In [40]:
opredictions[3][0]

array([-6.0766506 , -7.4476194 ,  1.0541167 , -0.34085742,  3.0790534 ,
       -1.7799082 ,  6.4770155 , -5.354231  , -4.1716385 , -6.706735  ],
      dtype=float32)

## Score

In [61]:
path = "exp/resnet50_cifar10/upstream"
scores = np.load(os.path.join(path, "scores.npy"))

In [62]:
print(scores.shape)
print(scores)

(1000, 1)
[[  1.80162631]
 [  8.89084055]
 [  7.45901781]
 [  5.04413927]
 [  5.2967743 ]
 [  8.69164166]
 [  7.94933754]
 [  3.37516871]
 [  7.23413452]
 [  2.26852094]
 [  9.20050679]
 [ -5.82263857]
 [  4.52021243]
 [  4.1335171 ]
 [  8.52653203]
 [  5.08101568]
 [  5.06492908]
 [  7.06957502]
 [  7.84153185]
 [ 11.43362777]
 [  6.0775415 ]
 [  7.18838459]
 [  7.59118801]
 [  9.40716306]
 [  8.79225941]
 [  8.71180138]
 [  3.63722296]
 [  6.21357684]
 [  9.43258023]
 [  8.41606929]
 [  6.54733125]
 [  9.16484196]
 [ -3.108648  ]
 [  8.81328636]
 [  7.94287507]
 [  7.66573123]
 [  6.59156851]
 [  6.39101881]
 [  7.45306951]
 [ -1.13474509]
 [  2.79521248]
 [ -2.0401252 ]
 [ -2.08963527]
 [ -0.80724557]
 [  9.75007711]
 [  1.69894016]
 [  7.76115982]
 [  9.58116824]
 [ 10.2246267 ]
 [ 10.16379952]
 [  8.30875147]
 [  7.6047741 ]
 [  4.29544152]
 [  7.73886319]
 [  8.34647498]
 [ -1.4358109 ]
 [  9.03932787]
 [ -6.13314799]
 [  2.37973004]
 [  7.80710677]
 [  9.08989358]
 [  2.80348955

## Plot

In [63]:
def load_data(savedir):
    """
    Load our saved scores and then put them into a big matrix.
    """
    global scores, keep, upstream_scores, upstream_keep
    scores = []
    keep = []

    for path in os.listdir(savedir):
        scores.append(np.load(os.path.join(savedir, path, "scores.npy")))
        keep.append(np.load(os.path.join(savedir, path, "keep_sampled.npy")))
    scores = np.array(scores)
    keep = np.array(keep)

    upstream_scores = np.load(os.path.join(savedir, "upstream", "scores.npy"))
    upstream_keep = np.load(os.path.join(savedir, "upstream", "keep_sampled.npy"))

    return scores, keep, upstream_scores, upstream_keep

In [64]:
path = "exp/resnet50_cifar10"
scores, keep, upstream_scores, upstream_keep = load_data(path)


In [66]:
print(upstream_scores.shape)
print(upstream_scores)

[[  1.80162631]
 [  8.89084055]
 [  7.45901781]
 [  5.04413927]
 [  5.2967743 ]
 [  8.69164166]
 [  7.94933754]
 [  3.37516871]
 [  7.23413452]
 [  2.26852094]
 [  9.20050679]
 [ -5.82263857]
 [  4.52021243]
 [  4.1335171 ]
 [  8.52653203]
 [  5.08101568]
 [  5.06492908]
 [  7.06957502]
 [  7.84153185]
 [ 11.43362777]
 [  6.0775415 ]
 [  7.18838459]
 [  7.59118801]
 [  9.40716306]
 [  8.79225941]
 [  8.71180138]
 [  3.63722296]
 [  6.21357684]
 [  9.43258023]
 [  8.41606929]
 [  6.54733125]
 [  9.16484196]
 [ -3.108648  ]
 [  8.81328636]
 [  7.94287507]
 [  7.66573123]
 [  6.59156851]
 [  6.39101881]
 [  7.45306951]
 [ -1.13474509]
 [  2.79521248]
 [ -2.0401252 ]
 [ -2.08963527]
 [ -0.80724557]
 [  9.75007711]
 [  1.69894016]
 [  7.76115982]
 [  9.58116824]
 [ 10.2246267 ]
 [ 10.16379952]
 [  8.30875147]
 [  7.6047741 ]
 [  4.29544152]
 [  7.73886319]
 [  8.34647498]
 [ -1.4358109 ]
 [  9.03932787]
 [ -6.13314799]
 [  2.37973004]
 [  7.80710677]
 [  9.08989358]
 [  2.80348955]
 [  0.52

In [67]:
print(upstream_keep.shape)
print(upstream_keep)

(1000,)
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True 

In [68]:
print(scores.shape)
print(scores)

(128, 1000, 1)
[[[ 0.07979911]
  [ 2.0123501 ]
  [ 5.86277897]
  ...
  [ 5.40763526]
  [ 0.81240715]
  [ 6.64311283]]

 [[ 2.92488602]
  [ 5.28626149]
  [ 6.2013628 ]
  ...
  [ 7.9306727 ]
  [ 1.327138  ]
  [ 4.16519172]]

 [[-0.58238898]
  [ 4.71298025]
  [ 6.90209837]
  ...
  [ 7.83007834]
  [ 3.06220088]
  [ 7.07026942]]

 ...

 [[ 0.94472266]
  [ 5.99466174]
  [ 4.91848345]
  ...
  [ 5.66715711]
  [ 3.32593956]
  [ 3.85878869]]

 [[ 0.51993905]
  [ 7.42040337]
  [ 6.95659164]
  ...
  [ 8.96653789]
  [ 3.25999698]
  [ 2.15013316]]

 [[ 2.79387071]
  [ 6.01316057]
  [ 7.35496446]
  ...
  [ 7.13079689]
  [ 2.20434512]
  [ 6.89572839]]]


In [69]:
print(keep.shape)
print(keep)

(128, 1000)
[[False  True  True ...  True  True False]
 [False False False ...  True  True  True]
 [False  True False ... False False False]
 ...
 [ True False  True ...  True  True False]
 [False False  True ... False False  True]
 [False False  True ...  True False False]]
